### ISSUE TITLE
Installation issue on NVIDIA GRID instance

### ISSUE THREAD

**Issue by generein** [LyceanEM/LyceanEM-Python#6]
Hello,

I am having issues installing LyceanEM and especially its open3d dependency on an [NVIDIA GRID](https://www.nvidia.com/en-gb/data-center/virtual-pc/) instance.

Steps followed (as per [documentation](https://documentation.lyceanem.com/en/latest/installation.html)):

- Install CUDA
- Install Anaconda
- Create new environment (attempted with Python 3.7, 3.8 and 3.9)
- Conda install (from conda-forge) cudatoolkit and cupy
- Pip install of open3d (conda is no longer supported)

All appears to go correctly up to this point, no errors in the installation. 
However, checking the installation with `python -c "import open3d as o3d; print(o3d.__version)"` results in an error:

```
Traceback (most recent call last):
   File "<string>", line 1, in <module>
   File "<C:\Anaconda\envs\lyceanem\lib\site-packages\open3d\__init__.py", line 94, in <module>
       from open3d.cpu.pybind import (core, camera, date, geometry, io, pipelines,
ImportError: DLL load failed while importing pybind: The specified module could not be found.
```

Are there any recipes to work around this?

**Comment by generein** [comment]
The sequence is, starting from scratch:

```
conda config --add channels conda-forge
conda create --name lyceanem python=3.9
conda activate lyceanem
conda install cudatoolkit
conda install cupy
pip install open3d
python -c "import open3d as o3d; print(o3d.__version__)"
```

This results in the error as above. @LyceanEM thought that a specific o3d version/environment could work for this virtualised deployment, based on prior experience.

**Comment by tf17270** [comment]
Unfortunately your script works on my system so debugging it is going to be a bit trickier

First I would encourage again to install pip into your conda environment before pip installing to make sure that the open3d is linked to the conda environment path and not the main path environment variable ie 
conda install pip
conda activate lyceanem
pip install open3d

I would want to try the version Tim originally used 
pip install open3d=0.7.0

Unfortunately this seems a somewhat common unresolved error with open3d that you can find on the open3ds github among other forums, some suggestions I found there include reinstalling cuda, my suggestion of pip and installing pybind11. I will try and get access to a grid instance to try debugging in a more similar environment to yours

**Comment by tf17270** [comment]
@generein Any updates on this?

**Comment by generein** [comment]
Yes, I tried:

*  conda install pip etc. - still the same error
* conda install pybind11 - still the same error
* pip install open3d=0.7.0 - an error message that it cannot find/install this
 
 :disappointed:

**Comment by tf17270** [comment]
> Yes, I tried:
> 
> * conda install pip etc. - still the same error
> * conda install pybind11 - still the same error
> * pip install open3d=0.7.0 - an error message that it cannot find/install this
> 
> 😞

could you try this please

conda install pip
conda activate lyceanem
pip install open3d

**Comment by tf17270** [comment]
In each instance have you created a new environment and deleted the old one to make sure that there not conflicting with one another? 

I have found a few threads linked to this error with open3d in my googling who all seemed to solve the issue by one of removing cuda and reinstalling (in one case from nvidia instead of conda (this toolkit is more complete and more recently updated than the conda version)) removing python or conda and reinstalling  or building from source. 

As it is unclear which if  any of these would work I try starting from as clean a slate as possible and see what happens (ie remove python conda etc as this encompasses a number of the solutions people have had)
 I would also recommend raising an issue on open3d as this is seemingly common so there developers would likely like to know and perhaps they will be able to fix it.
 
 
Alternatively lyceanem will be moving away from open3d in the medium future ( in the next 6 months) so the issue may solve itself. Apologies for not being more help

**Comment by tf17270** [comment]
@generein Just an update open3d is no-longer a requirement for LyceanEM so you're issue should be resolved

**Comment by generein** [comment]
I can confirm this is indeed the case - I am able to install and run on an Nvidia Grid instance with v0.0.7 (though ran into #12 )
